config/routes.rb
Rails.application.routes.draw do
  devise_for :clinicians
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'pages#home'
  devise_scope :clinician do
    get "/clinicians/sign_in", to: "devise/sessions#new"
    get "/clinicians/sign_out", to: "devise/sessions#destroy"
  end

 
  resources :clinicians do
     resources :cases do
      resources :notes
    end
  end
  get 'clinicians/:clinician_id/cases/:id/attachments' => 'attachments#index', as: :documents
  get 'clinicians/:clinician_id/cases/:id/add_collaborator' => 'cases#add_collaborator', as: :add_collaborator
  get 'clinicians/:clinician_id/cases/:id/assign_collaborator/:collaborator' => 'cases#assign_collaborator', as: :assign_collaborator

end

app/models/clinician.rb
class Clinician < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    validates :name, presence: true
    validates :email, presence: true
    has_many :cases, through: :patients
    has_many :patients
    accepts_nested_attributes_for :cases
    has_many :notes
end

app/controllers/clinicians_controller.rb
class CliniciansController < ApplicationController
  before_action :authenticate_clinician!

  def clinician_params    
    params.require(:clinician).permit(:name, :email, :specialty, cases_attributes: [:name, :diagnosis, :age, :gender, 
      :disease_characteristic, :treatment_history, :past_medical_history, :id])
  end

  def show
    @clinician = Clinician.find(params[:id])
    @allowed = @clinician.id == current_clinician.id
  end
  
  def edit
    @clinician_id = params[:id]
    @clinician = Clinician.find(@clinician_id)
    if @clinician.id != current_clinician.id
      flash[:warning] = "You cannot edit another clinician's profile"
      redirect_to clinician_path(@clinician_id)
    else
      @clinician = Clinician.find(@clinician_id)
    end
  end
  
  def update
    @clinician_id = params[:id].to_i
    @clinician = Clinician.find(@clinician_id)
    if @clinician.update(clinician_params)
      flash[:success] = "Profile was succesfully updated"
      redirect_to clinician_path(@clinician_id)
    else
      render 'edit'
    end
  end

end

app/helpers/clinicians_helper.rb
module CliniciansHelper
end

app/views/clinicians/_form.html.erb
<%= render 'shared/errors', obj: @clinician %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@clinician, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :name %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of clinician", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "123@abc.com" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :specialty %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :specialty, rows: 8, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
    
  </div>
</div>

app/views/clinicians/edit.html.erb
<h1 class="text-center">Edit Your Profile</h1>
<%= render 'form' %>

app/views/clinicians/index.html.erb
<h1 class="text-center">Clinicians</h1>

<% @clinicians.each do |c| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="clinician-name">
          Name: <%= link_to c.name, clinician_path(c) %>
        </div>

        <div class="clinician-email">
          Email: <%= c.email %>
        </div>
        <div class="clinician-specialty">
          Specialty: <%= c.specialty %>
        </div>
        <!-- the button used to select as collaborator, see case view -->
        <div class="clinician-select">
          <% if session[:case_id] %>
          <%= link_to "Select as collaborator", assign_collaborator_path(current_clinician.id, session[:case_id], c) , { class: "btn btn-sm btn-primary" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/clinicians/new.html.erb
<h1 class="text-center">Create a new clinician</h1>
<%= render 'form' %>

app/views/clinicians/show.html.erb
<h2 class="text-center">Clinician: <strong><%= @clinician.name %></strong></h3>
<div class="well col-xs-8 col-xs-offset-2">
  
  <h4><strong>Email: <%= @clinician.email %></strong></h4>
  <h4><strong>Specialty:</strong></h4>
  <%= simple_format(@clinician.specialty) %>
  <% if @allowed %>
    <div class="clinician-action">
      <%= link_to "Edit Profile", edit_clinician_path, class: "btn btn-xs btn-primary" %>
   </div>
  <% end %>
</div>