config/routes.rb
Rails.application.routes.draw do
  devise_for :clinicians
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'pages#home'
  devise_scope :clinician do
    get "/clinicians/sign_in", to: "devise/sessions#new"
    get "/clinicians/sign_out", to: "devise/sessions#destroy"
  end

 
  resources :clinicians do
     resources :cases do
      resources :notes
    end
  end
  get 'clinicians/:clinician_id/cases/:id/attachments' => 'attachments#index', as: :documents
  get 'clinicians/:clinician_id/cases/:id/add_collaborator' => 'cases#add_collaborator', as: :add_collaborator
  get 'clinicians/:clinician_id/cases/:id/assign_collaborator/:collaborator' => 'cases#assign_collaborator', as: :assign_collaborator

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer>
    <small>
      Copyright &copy; <a href="https://github.com/ProvidenceXz/Trinity-Health">Trinity Health Team</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", "#" %></li>
        <li><%= link_to "Contact", "#" %></li>
        <li><%= link_to "CS169", "#" %></li>
      </ul>
    </nav>
  </footer>
</div><!-- /.container -->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid"></div>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Trinity-Health", root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if clinician_signed_in? %>
          <li><%= link_to "My Cases", clinician_cases_path(current_clinician.id) %></li>
          <li><%= link_to "Add Case", new_clinician_case_path(current_clinician.id) %></li>
        <% end %>
      </ul>

      <% if clinician_signed_in? %>
        <%= form_tag clinician_cases_path(current_clinician), :method => 'get', :class => "navbar-form navbar-left" do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search case..", :class => "form-control" %> 
            <%= submit_tag "Search", :class => "btn btn-default", :name => 'submit', :id => 'submit' %>
          </div>
        <% end %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% unless clinician_signed_in? %>
          <li><a href="/clinicians/sign_in">Log in</a></li>
        <% end %>
        <% if clinician_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><%= current_clinician.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Profile", clinician_path(current_clinician) %></li>
              <li><%= link_to "My Cases", clinician_cases_path(current_clinician) %></li>
              <li><a href="#">Messages</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="/clinicians/sign_out">Log out</a></li>
            </ul>
          </li>
        <% end %>
                                                          
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrinityHealth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<!--  <#%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
<%= javascript_include_tag 'application' %>
  <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
<%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>


</body>
</html>